apiVersion: v1
kind: Namespace
metadata:
  name: lift-os
  labels:
    name: lift-os
    environment: production
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: lift-os-quota
  namespace: lift-os
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "10"
    services: "20"
    secrets: "10"
    configmaps: "10"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: lift-os-limits
  namespace: lift-os
spec:
  limits:
  - default:
      cpu: "500m"
      memory: "512Mi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    type: Container